services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    volumes:
      - .docker/apps/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=coval
      - POSTGRES_USER=coval
      - POSTGRES_DB=coval