version: '3.9'

services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    volumes:
      - .docker/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=coval
      - POSTGRES_USER=coval
      - POSTGRES_DB=coval